
# SEO settings
title: "SA"
title2: "S" # default: ""
description: "Personal Blog"
keywords: "Agile, Software Development, Mobile Apps, Website Development, DevOps"
url: syafrizaladi.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-111697931-1
repo: syafrizaladi.github.io
disqus_shortname: "hnbloggithub"
twitter_username: "syafrizaladi"
comments: true

# Build settings
permalink   : /:categories/:year/:month/:day/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Rizal"
  job      : "Scrum Master"
  bio      : "Proses Senantiasa Belajar sehingga mencapai suatu titik Senantiasa Menjadi"
  thumb    : /images/author.jpg
  email    : syafrizaladi@saktia.com
  url      : http://syafrizaladi.github.io
  github   : http://github.com/syafrizaladi
  twitter  : http://twitter.com/syafrizaladi
  facebook : https://www.facebook.com/Syafrizal.Adi.Saktia
  linkedin : https://www.linkedin.com/in/saktia/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@syafrizaladi"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
